databases:
  - name: portfoliosdb
    plan: free
    databaseName: portfolios
    user: portfolios

services:
  - type: web
    plan: free
    name: portfolios
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn portfolios.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfoliosdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4